### ISSUE TITLE
Can someone confirm this is working ?

### ISSUE THREAD

**Issue by jetonr** [ryangiglio/jquery-tweetMachine#18]
I have downloaded and added my app details but no tweets show up in sample!

**Comment by ryangiglio** [comment]
It's still working for me. Are you running it on a server? It needs to be in a server environment for the php component to run.

If that's good, do you have a live demo that I could look at?

**Comment by jetonr** [comment]
Was testing on xampp running php

**Comment by ryangiglio** [comment]
Is there any way for me to see a live version of your code? I'd be able to figure out what wrong much easier that way.

Otherwise, do you see any Javascript errors in your dev console? If not, do you see repeated calls to getFromTwitter.php in the Network panel (in Chrome, at least)? The response that the page is returning should tell us something about what's wrong.

**Comment by jetonr** [comment]
SyntaxError: Unexpected identifier which refers to endpoint: 'statuses/user_timeline',

**Comment by ryangiglio** [comment]
Are you getting that as a Javascript error, or in the Network panel?

**Comment by jetonr** [comment]
No in chrome i have javascript error notifier. I didn't change anything on the script only the twitter oauth secret and tokekns

**Comment by jetonr** [comment]
Just tested online works great :) 
It must be some problem with xampp on localhost .
